variables:
  TF_ROOT: ${CI_PROJECT_DIR}/terraform

before_script:
  - cd ${TF_ROOT}
  - pwd

stages:
  - prepare
  - validate
  - build
  - deploy


init:
  stage: prepare
  script:
    - find ../ -maxdepth 1 -name '*.json' -print0 | xargs -t0n1 packer validate

validate:
  stage: validate
  script:
    - terraform init && terraform validate


build:
  stage: build
  script:
    - find ../ -maxdepth 1 -name '*.json' -print0 | xargs -t0n1 packer build 
    - terraform init && TF_LOG=INFO terraform apply --auto-approve
  only:
    - dev

deploy:
  stage: deploy
  script:
    – find ../ -maxdepth 1 -name '*.json' -print0 | xargs -t0n1 packer build
  
  dependencies:
    - validate
    - build
  when: manual
  only:
    - master
